services:
 
  flask-app-1:
    image: arunkumar2202/devops-flask-app:${APP1_IMAGE_TAG:-latest}
    container_name: flask-app-1
    restart: always
    ports:
      - "8001:8000"
    environment:
      INSTANCE_NAME: flask-app-1
      APP_VERSION: "1.0"
 
  flask-app-2:
    image: arunkumar2202/devops-flask-app:${APP2_IMAGE_TAG:-latest}
    container_name: flask-app-2
    restart: always
    ports:
      - "8002:8000"
    environment:
      INSTANCE_NAME: flask-app-2
      APP_VERSION: "1.0"





